### ISSUE TITLE
Problems to update the PWD List

### ISSUE THREAD

**Issue by Gen-log** [lithnet/ad-password-protection#116]
I've downloded the newest haveibeenpwd password list, via haveibeenpwned-downloader.
When I try to update the list on my DC I get this error:

Import-CompromisedPasswordHashes : The file that is to be replaced cannot be removed.

+ Import-CompromisedPasswordHashes -Filename "x:\temp\pwnedpasswords_nt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-CompromisedPasswordHashes], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Lithnet.ActiveDirectory.PasswordProtection.PowerShell.ImportCompro
   misedPasswordHashes

**Comment by ryannewington** [comment]
It sounds like something has locked open the files in the store folder. If you are using dfs-r make sure you pause replication. Otherwise you could try an AV exclusion for the store folder. If that doesn't work you may need to resort to using something like procmon to determine what process is accessing the store files so you can stop it.

FYI the latest version of LPP has a sync-hashesfromhibp cmdlet to import directly without having to use the hibp import tool.

**Comment by Gen-log** [comment]
ok - I already checked the AV Software, but will check it again.

> sync-hashesfromhibp

WOW! That's what I'm searching for! Thanks!
