### ISSUE TITLE
MSI available for installation?

### ISSUE THREAD

**Issue by Rbcwenum** [lithnet/ad-password-protection#122]
hi, we are trying to get the latest (1.1.53) version installed. On server GUI we can use the .exe without any issues. On server Core however we run into issues that the installation is blocked, apparently through Software Protection. We dont have that enabled, so kinda weird.
The unpacked MSI is installing fine. As we usually repackage the software so we can install it through Chocolatey, our question is.

- Is there a MSI download available for the later versions?
- If not, if we extract the .exe, there are a .msi and a .cab file there. Are both required for the installation?

Thanks!

**Comment by ryannewington** [comment]
You should be able to install the EXE on server core using the `/quiet /qn` switches

LithnetPasswordProtection-1.1.53.exe /quiet /qn InstallLevel=4

**Comment by darkpixel** [comment]
Yeah...where'd the MSI files go?  I have an old version installed at several locations, but the MSI files are gone.

Windows Installer files are so much easier to automatically deploy without bizarre non-standard switches.

**Comment by darkpixel** [comment]
Ugh.  It looks like it's actually an MSI file wrapped into an EXE for no good reason.
How to get what you want:
* Download the EXE to your workstation
* Double-click it and complete the setup
* Look in the registry under ```HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\```
* Search for "lithnet"
* Look under the ```InstallProperties``` folder for ```LocalPackage```
* Go grab the MSI from c:\windows\installer\whatever.msi
* Deploy the MSI as God intended

**Comment by ryannewington** [comment]
There's actually a good reason we had to move to an EXE. 

MSI files don't have a native mechanism for installing dependent packages.

They do have "merge modules" which allow you to integrate another set of assemblies with your own.

We used to use the visual C runtime merge modules, but these have since [been deprecated by Microsoft](https://learn.microsoft.com/en-us/cpp/windows/redistributing-components-by-using-merge-modules?view=msvc-170).

So we had to move to an exe based installer, which checks and installs the pre-reqs, before launching the MSI. We didn't particularly want to fork out thousands of dollars for a third party installer app that can do this either. Especially for an open source product which we do not charge for.

This decision was made to carefully balance the needs of our diverse user base, who are not all experts in installer technology, and who need a path to success with a single click install. This helps them get up and running and protect their environments without friction.

The capability to do silent installs has not been removed, and remains for those that need it. All MSI command line args are valid and get passed straight through.

If God's intent is for MSI to be installed natively everywhere, then only they have the power to direct Microsoft to update their technology to include native support for dependency chaining. If you are in direct communication with said higher being, feel free to refer them here and I'll provide my other wishlist items for Microsoft to fix in MSIs while they are at it! 🙂

The feedback is appreciated. We'll get the documentation updated to make the process clearer for these sorts of scenarios. 

There's nothing wrong with extracting and using the MSI directly, as long as you are sure the prerequisites are installed.

**Comment by darkpixel** [comment]
Sure--I totally understand that.
Prerequisites (like MSVCRT) can be installed automatically by most deployment systems before trying to install Lithnet.
That's how we did our initial deployment, and I just finished our first server to the latest version automatically for testing.

**Comment by CrookedJ** [comment]
> Ugh. It looks like it's actually an MSI file wrapped into an EXE for no good reason. How to get what you want:
> 
> * Download the EXE to your workstation
> * Double-click it and complete the setup
> * Look in the registry under `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\`
> * Search for "lithnet"
> * Look under the `InstallProperties` folder for `LocalPackage`
> * Go grab the MSI from c:\windows\installer\whatever.msi
> * Deploy the MSI as God intended

You can actually just start the installer (don't complete it) and then grab the msi from `%APPDATA%\Lithnet\PasswordProtection1.1.57.0\install\`

**Comment by darkpixel** [comment]
Yeah--that's what we ended up doing.  It's a major pain.
Thankfully there aren't new releases every year... ;)
