### ISSUE TITLE
add testing AD password for banned words as well as Comprimised

### ISSUE THREAD

**Issue by EnviableOne** [lithnet/ad-password-protection#33]
The test-IsadUserpasswordCompromised is great for the audit function, but it would be greatly enhanced if you could test the curent AD passwords against the banned word list, or even the get-filterResult
this would allow an organisation to assess the impact of applying there settings better and make it possible to do a full password audit by plugging the new command into the wiki script

**Comment by ryannewington** [comment]
I’d love to be able to do that, but the problem we have is the passwords in AD are sorted using a one-way hash. They can’t be returned to their plain text equivalent (without brute forcing). So we can check for compromised passwords, because we check for a matching hash in our database. 

Unfortunately all the other checks require that we know the plain-text password, which is why we can only test them at password change time. Windows allows us to test the password just before it hashes it and saves it. Once it’s saved, it’s no longer usable. 

The only way to know if you organisation is using good passwords, is to set up your lpp policy, and push a rolling forced password change on all users, or wait until everyone’s password has expired. Not ideal but that’s how we did it for 180k users.

**Comment by tekcap** [comment]
Could always hash the plain text passwords on the fly?
